version: '2'

services:
  devops:
    container_name: devops
    image: anmolnagpal/devops:1.1.0
    mem_limit: 2g
    memswap_limit: 2g
    cpu_shares: 30
    privileged: true
    ports:
      - "13:22" # ssh
    volumes:
      - ./bin/devops:/image/
      - ~/Workspace/:/var/www/
      - ~/Workspace/data/devops-log:/var/log
      - ./bin/devops/etc/sshd.conf:/etc/ssh/sshd_config
      - ~/.ssh:/root/.ssh
      - ./bin/devops/etc/zshrc:/root/.zshrc
      - ./bin/devops/etc/zsh/aliases.conf:/root/.aliases
      - ./bin/devops/etc/zsh/extra.conf:/root/.extra
      - ~/.ssh:/home/www-data/.ssh
      - ./bin/devops/etc/zshrc:/home/www-data/.zshrc
      - ./bin/devops/etc/zsh/aliases.conf:/home/www-data/.aliases
      - ./bin/devops/etc/zsh/extra.conf:/home/www-data/.extra
      - ./bin/devops/php/php.ini:/etc/php/7.1/fpm/php.ini
      - ./bin/devops/php/pool:/etc/php/7.1/fpm/pool.d
    networks:
      dev_net_devops:
        ipv4_address: 10.13.0.13

networks:
  dev_net_devops:
    driver: bridge
    ipam:
     config:
       - subnet: 10.13.0.0/16
         gateway: 10.13.0.1


