version: '2'

services:
  DevOps:
    container_name: DevOps
    image: anmolnagpal/devops:1.0.0
    mem_limit: 2g
    memswap_limit: 2g
    cpu_shares: 30
    privileged: true
    ports:
      - "2228:22" # ssh
      - "9008:9003" # supervisor admin
    volumes:
      - ./bin/php7:/image/
      - ~/Workspace/:/var/www/
      - ~/Workspace/data/php-log:/var/log/php
      - ./bin/php7/etc/sshd.conf:/etc/ssh/sshd_config
      - ~/.ssh:/root/.ssh
      - ./bin/php7/etc/zshrc:/root/.zshrc
      - ./bin/php7/etc/zsh/aliases.conf:/root/.aliases
      - ./bin/php7/etc/zsh/extra.conf:/root/.extra
      - ~/.ssh:/home/www-data/.ssh
      - ./bin/php7/etc/zshrc:/home/www-data/.zshrc
      - ./bin/php7/etc/zsh/aliases.conf:/home/www-data/.aliases
      - ./bin/php7/etc/zsh/extra.conf:/home/www-data/.extra
      - ./bin/php7/php/php.ini:/etc/php/7.1/fpm/php.ini
      - ./bin/php7/php/php-fpm.conf:/etc/php/7.1/fpm/php-fpm.conf
      - ./bin/php7/php/pool:/etc/php/7.1/fpm/pool.d
    networks:
      dev_net_packages:
        ipv4_address: 10.60.0.5

networks:
  dev_net_packages:
    driver: bridge
    ipam:
     config:
       - subnet: 10.60.0.0/16
         gateway: 10.60.0.1


