version: 2
jobs:
  build:
    machine: true
    working_directory: ~/devops-machine

    steps:
      - checkout
      - run:
          name: build the application image
          command: docker build -t anmolnagpal/devops:latest ./docker-image/.
